micronaut:
  application:
    name: mn03


datasources:
  default:
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb


jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
    entity-scan:
      packages:
        com.company.domain


netty:
  default:
    allocator:
      max-order: 3


flyway:
  datasources:
    default:
      enabled: true
