micronaut:
  application:
    name: mn03
datasources:
  default:
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: none
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true
